# Generated by Django 6.1 on 2026-08-27 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApologeticsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('EUCHARIST', 'Real Presence in the Eucharist'), ('CONFESSION', 'Sacrament of Reconciliation'), ('RETURNING', 'Returning to the Catholic Church'), ('CHURCH_FATHERS', 'Early Church History & Sacred Tradition'), ('MARY_SAINTS', 'Mary, Saints & Intercession'), ('BIBLE_CHURCH', 'Scripture & Church Authority')], default='EUCHARIST', max_length=20)),
                ('short_answer', models.TextField(help_text='Quick summary / TL;DR')),
                ('detailed_explanation', models.TextField(help_text='Biblical, theological, and logical breakdown')),
                ('scripture_citations', models.TextField(blank=True, help_text='e.g. John 6:51-58, 1 Cor 11:23-29')),
                ('church_fathers_quote', models.TextField(blank=True, help_text='Quotes from St. Ignatius, Justin Martyr, Augustine, etc.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='Sparkles', help_text='Lucide icon name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('scripture_reference', models.CharField(max_length=150)),
                ('scripture_text', models.TextField()),
                ('saint_name', models.CharField(max_length=150)),
                ('saint_feast_or_title', models.CharField(blank=True, max_length=150)),
                ('saint_quote', models.TextField()),
                ('reflection_body', models.TextField()),
                ('closing_prayer', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PrayerIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A Fellow Pilgrim', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(choices=[('FAITH_RETURN', 'Return to Faith & Family'), ('HEALING', 'Physical & Mental Healing'), ('FAMILY', 'Marriage & Family Peace'), ('VOCATIONS', 'Priesthood & Religious Life'), ('PEACE', 'World Peace & Protection'), ('THANKSGIVING', 'Thanksgiving & Praise')], default='FAITH_RETURN', max_length=20)),
                ('intention_text', models.TextField()),
                ('is_candle_lit', models.BooleanField(default=True)),
                ('prayers_count', models.PositiveIntegerField(default=1, help_text="Count of pilgrims who tapped 'I Prayed For You'")),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Miracle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('location_city', models.CharField(max_length=150)),
                ('location_country', models.CharField(max_length=150)),
                ('year_occurred', models.CharField(help_text="e.g. '750 AD', '1996', '2008'", max_length=50)),
                ('century', models.CharField(default='Modern', help_text="e.g. '8th Century', '20th Century', '21st Century'", max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='miracles/')),
                ('cover_image_url', models.URLField(blank=True, help_text='Fallback external URL or Cloudinary URL', max_length=500)),
                ('relic_image_url', models.URLField(blank=True, max_length=500)),
                ('audio_narration_url', models.URLField(blank=True, max_length=500)),
                ('summary', models.TextField(help_text='Concise 2-3 sentence overview for cards and meta descriptions')),
                ('full_story', models.TextField(help_text='Detailed narrative of how the miracle took place')),
                ('scientific_summary', models.TextField(help_text='Summary of forensic/medical discoveries')),
                ('blood_type', models.CharField(default='AB+', help_text='e.g. AB Positive (Universal Recipient)', max_length=50)),
                ('tissue_type', models.CharField(default='Myocardium (Left Ventricle Heart Muscle)', help_text='Tissue pathology finding', max_length=255)),
                ('white_blood_cells_present', models.BooleanField(default=True, help_text='Indicates tissue was living / under severe trauma at moment of study')),
                ('forensic_lead_scientist', models.CharField(blank=True, help_text='e.g. Dr. Edoardo Linoli, Dr. Frederic Zugibe (Columbia University)', max_length=255)),
                ('scientific_notes', models.TextField(blank=True, help_text='Additional scientific laboratory observations')),
                ('church_approval', models.CharField(choices=[('VATICAN', 'Vatican Formally Approved'), ('DIOCESAN', 'Diocesan Bishop Approved'), ('HISTORICAL', 'Historically Documented & Vetted')], default='VATICAN', max_length=20)),
                ('key_spiritual_message', models.TextField(blank=True)),
                ('scripture_verse', models.CharField(default="John 6:51 - 'I am the living bread that came down from heaven.'", max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miracles', to='core.category')),
            ],
            options={
                'ordering': ['-is_featured', 'year_occurred'],
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=100)),
                ('author_location', models.CharField(blank=True, max_length=150)),
                ('story', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_miracle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to='core.miracle')),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-created_at'],
            },
        ),
    ]
