# Generated by Django 6.1 on 2026-08-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('FEAST', 'Liturgical Feast'), ('ADORATION', 'Eucharistic Adoration'), ('PARISH', 'Parish Event'), ('PRAYER', 'Prayer & Devotion'), ('OTHER', 'Other')], default='PARISH', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
