# Generated by Django 5.2.17 on 2026-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miracle',
            name='audio_narration_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='miracle',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Direct image URL (e.g. Unsplash, Wikimedia, Cloudinary, Imgur)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='miracle',
            name='relic_image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
