# Generated by Django 5.2.17 on 2026-09-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_miracle_audio_narration_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miracle',
            name='cover_image_url',
        ),
    ]
