# Generated by Django 5.2.17 on 2026-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_miracle_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='adoration_youtube_url',
            field=models.URLField(blank=True, default='', help_text='Paste the YouTube URL of the live adoration stream. Accepted formats:\n  https://www.youtube.com/watch?v=VIDEO_ID\n  https://youtu.be/VIDEO_ID\n  https://www.youtube.com/live/VIDEO_ID\nLeave blank to hide the live stream section on the Adoration page.', max_length=500),
        ),
    ]
