# Generated by Django 5.2.17 on 2026-09-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_adoration_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EucharisticPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_title', models.CharField(help_text='Short title displayed on the prayer tab button (e.g. "Anima Christi", "Tantum Ergo")', max_length=100)),
                ('title', models.CharField(help_text='Full title heading displayed above the prayer text (e.g. "Anima Christi (Soul of Christ)")', max_length=200)),
                ('content', models.TextField(help_text='Full prayer text. Stanzas and line breaks will be preserved.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this prayer tab appears (lower numbers appear first).')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this prayer without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sacred Eucharistic Prayer',
                'verbose_name_plural': 'Sacred Eucharistic Prayers',
                'ordering': ['order', 'id'],
            },
        ),
    ]
